### ISSUE TITLE
Data formatter tries to start on port 5000, which is a port used by macOS, lots of other build errors

### ISSUE THREAD

**Issue by sammcj** [microsoft/data-formulator#43]
Data formatter tries to start on port 5000, however port 5000 is an important port used by macOS for Airplay.

This causes the app to crash.

```
data_formulator
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator/agents/agent_utils.py:16: SyntaxWarning: invalid escape sequence '\W'
  var_name = re.sub('\W|^(?=\d)','_', var_str)
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator/agents/agent_code_explanation.py:77: SyntaxWarning: invalid escape sequence '\h'
  user_query = f"[CONTEXT]\n\n{data_summary}\n\n[CODE]\n\here is the transformation code: {code}\n\n[EXPLANATION]\n"
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator
 * Serving Flask app 'data_formulator.app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
On macOS, try disabling the 'AirPlay Receiver' service from System Preferences -> General -> AirDrop & Handoff.
```

Also note that --help does not provide any options for specifying the port:

```
$ data_formulator --help
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator
 * Serving Flask app 'data_formulator.app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
On macOS, try disabling the 'AirPlay Receiver' service from System Preferences -> General -> AirDrop & Handoff.
```

I noticed the app uses Flask, but setting the Flask port does not seem to work either:

```
 FLASK_RUN_PORT=5009 data_formulator
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator
 * Serving Flask app 'data_formulator.app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
On macOS, try disabling the 'AirPlay Receiver' service from System Preferences -> General -> AirDrop & Handoff.
```

Looking at the [source code](https://github.com/microsoft/data-formulator/blob/main/py-src/data_formulator/app.py#L454) I see it also appears to use the python arg parser and provides a `-p` or `--port`, however this does not work:

```
data_formulator -p 5009
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator
 * Serving Flask app 'data_formulator.app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
On macOS, try disabling the 'AirPlay Receiver' service from System Preferences -> General -> AirDrop & Handoff.
```

Cloning from source and running `./local_server.sh` fails as the script has not been committed with the execute bit, after doing this the -p arg is still ignored:

```
./local_server.sh
zsh: permission denied: ./local_server.sh

chmod +x local_server.sh

./local_server.sh
/Users/samm/git/data-formulator/py-src/data_formulator/agents/agent_utils.py:16: SyntaxWarning: invalid escape sequence '\W'
  var_name = re.sub('\W|^(?=\d)','_', var_str)
/Users/samm/git/data-formulator/py-src/data_formulator/agents/agent_code_explanation.py:77: SyntaxWarning: invalid escape sequence '\h'
  user_query = f"[CONTEXT]\n\n{data_summary}\n\n[CODE]\n\here is the transformation code: {code}\n\n[EXPLANATION]\n"
/Users/samm/git/data-formulator/py-src/data_formulator
 * Serving Flask app 'py-src/data_formulator/app.py'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
On macOS, try disabling the 'AirPlay Receiver' service from System Preferences -> General -> AirDrop & Handoff.
(samm) [mainU] ~/git/data-formulator [1] $ ./local_server.sh -p 5009
/Users/samm/git/data-formulator/py-src/data_formulator
 * Serving Flask app 'py-src/data_formulator/app.py'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
On macOS, try disabling the 'AirPlay Receiver' service from System Preferences -> General -> AirDrop & Handoff.
```

After editing the source to change the port, the application starts, but loading the page fails:

```
./local_server.sh -p 5009
/Users/samm/git/data-formulator/py-src/data_formulator
 * Serving Flask app 'py-src/data_formulator/app.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5009
 * Running on http://192.168.0.75:5009
Press CTRL+C to quit
/Users/samm/git/data-formulator/py-src/data_formulator/dist
/Users/samm/git/data-formulator/py-src/data_formulator/dist
[2024-10-24 22:57:24,252] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/git/data-formulator/py-src/data_formulator/app.py", line 172, in index_alt
    return send_from_directory(app.static_folder, "index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/app.py", line 765, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/app.py", line 740, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/git/data-formulator/py-src/data_formulator/app.py", line 178, in page_not_found
    return send_from_directory(app.static_folder, "index.html") #'Hello 404!' #send_from_directory(app.static_folder, "index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/flask/helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Additionally installing the npm packages fails due to broken dependencies:

```
npm i

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: data-formulator@0.1.0
npm error Found: react@18.2.0
npm error node_modules/react
npm error   react@"^18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^15.3.0 || ^16.0.0" from react-diff-viewer@3.1.1
npm error node_modules/react-diff-viewer
npm error   react-diff-viewer@"^3.1.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/samm/.npm/_logs/2024-10-24T11_58_42_446Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/samm/.npm/_logs/2024-10-24T11_58_42_446Z-debug-0.log
```

Using pnpm instead of npm seems to work around the dependencies issues, but after the app launches it crashes:

```
11:01:26 pm [vite] Internal server error: Failed to resolve import "@mui/system" from "src/views/SelectableDataGrid.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/samm/git/data-formulator/src/views/SelectableDataGrid.tsx:12:20
  19 |  import TableHead from '@mui/material/TableHead';
  20 |  import TableRow from '@mui/material/TableRow';
  21 |  import { Box } from '@mui/system';
     |                       ^
  22 |  import { useTheme } from '@mui/material/styles';
  23 |  import { alpha, Collapse, Divider, Paper, ToggleButton, Tooltip } from "@mui/material";
      at TransformPluginContext._formatError (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49255:41)
      at TransformPluginContext.error (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49250:16)
      at normalizeUrl (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64041:23)
      at async file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64173:39
      at async Promise.all (index 10)
      at async TransformPluginContext.transform (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64100:7)
      at async PluginContainer.transform (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49096:18)
      at async loadAndTransform (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51929:27)
      at async viteTransformMiddleware (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:61881:24)
11:01:26 pm [vite] Pre-transform error: Failed to resolve import "immer" from "src/app/dfSlice.tsx". Does the file exist?
```

![Image](https://github.com/user-attachments/assets/70548eb0-c613-4b97-892a-1e55307525f3)

Manually installing the immer package works, but then the app fails on another dependency:

```
[plugin:vite:import-analysis] Failed to resolve import "@mui/system" from "src/views/SelectableDataGrid.tsx". Does the file exist?

/Users/samm/git/data-formulator/src/views/SelectableDataGrid.tsx:12:20

19 |  import TableHead from '@mui/material/TableHead';
20 |  import TableRow from '@mui/material/TableRow';
21 |  import { Box } from '@mui/system';
   |                       ^
22 |  import { useTheme } from '@mui/material/styles';
23 |  import { alpha, Collapse, Divider, Paper, ToggleButton, Tooltip } from "@mui/material";
```

builds also fail:

```
pnpm run build

> data-formulator@0.1.0 build /Users/samm/git/data-formulator
> vite build

vite v5.4.10 building for production...
transforming (43) node_modules/.pnpm/react-redux@8.1.3_@types+react-dom@18.3.1_@types+react@18.3.12_react-dom@18.3.1_react@18.3.1__react@18.3.1_redux@4.2.1/node_modules/react-redux/es/utils/useSyncExternalStDeprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

✓ 996 modules transformed.
x Build failed in 1.29s
error during build:
[vite]: Rollup failed to resolve import "@mui/system" from "/Users/samm/git/data-formulator/src/views/ReactTable.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65589:17)
    at onwarn (file:///Users/samm/git/data-formulator/node_modules/.pnpm/@vitejs+plugin-react-swc@3.7.1_vite@5.4.10_@types+node@20.17.0_sass@1.80.4_/node_modules/@vitejs/plugin-react-swc/index.mjs:206:9)
    at onRollupWarning (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65619:5)
    at onwarn (file:///Users/samm/git/data-formulator/node_modules/.pnpm/vite@5.4.10_@types+node@20.17.0_sass@1.80.4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65284:7)
    at file:///Users/samm/git/data-formulator/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19393:13
    at Object.logger [as onLog] (file:///Users/samm/git/data-formulator/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:21119:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/samm/git/data-formulator/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20008:26)
    at file:///Users/samm/git/data-formulator/node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19966:26
 ELIFECYCLE  Command failed with exit code 1.
```

After manually adding `"@mui/system"` to package.json, pnpm install works, and the build completes.

The application then starts, although there are warnings in the console:

```
pnpm run start

> data-formulator@0.1.0 start /Users/samm/git/data-formulator
> vite

Re-optimizing dependencies because lockfile has changed

  VITE v5.4.10  ready in 108 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
```

If it helps - The final working package.json that built for me was:

```
{
    "name": "data-formulator",
    "type": "module",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "@emotion/react": "^11.13.3",
        "@emotion/styled": "^11.13.0",
        "@fontsource/roboto": "^4.5.8",
        "@mui/icons-material": "^5.16.7",
        "@mui/material": "^5.16.7",
        "@reduxjs/toolkit": "^1.9.7",
        "ag-grid-community": "^32.3.0",
        "ag-grid-enterprise": "^32.3.0",
        "ag-grid-react": "^32.3.0",
        "d3": "^7.9.0",
        "dompurify": "^3.1.7",
        "immer": "10.1.1",
        "localforage": "^1.10.0",
        "lodash": "^4.17.21",
        "markdown-to-jsx": "^7.5.0",
        "mui-markdown": "^1.2.2",
        "prettier": "^2.8.8",
        "prism-react-renderer": "^2.4.0",
        "prismjs": "^1.29.0",
        "react": "^18.3.1",
        "react-animate-height": "^3.2.3",
        "react-animate-on-change": "^2.2.0",
        "react-diff-viewer": "^3.1.1",
        "react-dnd": "^16.0.1",
        "react-dnd-html5-backend": "^16.0.1",
        "react-dom": "^18.3.1",
        "react-redux": "^8.1.3",
        "react-router-dom": "^6.27.0",
        "react-selectable-fast": "^3.4.0",
        "react-simple-code-editor": "^0.14.1",
        "react-split-pane": "^2.0.3",
        "react-vega": "^7.6.0",
        "react-virtuoso": "^4.12.0",
        "redux": "^4.2.1",
        "redux-persist": "^6.0.0",
        "typescript": "^5.6.3",
        "validator": "^13.12.0",
        "vega": "^5.30.0",
        "vega-embed": "^6.26.0",
        "vega-lite": "^5.21.0",
        "@mui/system": "6.1.5",
        "vm-browserify": "^1.1.2"
    },
    "scripts": {
        "start": "vite",
        "build": "vite build"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "devDependencies": {
        "@types/d3": "^7.4.3",
        "@types/lodash": "^4.17.12",
        "@types/node": "^20.17.0",
        "@types/prismjs": "^1.26.5",
        "@types/react": "^18.3.12",
        "@types/react-dom": "^18.3.1",
        "@vitejs/plugin-react-swc": "^3.7.1",
        "sass": "^1.80.4",
        "vite": "^5.4.10"
    }
}
```

**Comment by Chenglong-MS** [comment]
Yes, the new pypi deployment is complete.

`pip install data-formulator` would point to version 0.1.3.3 which includes port option and a new support of providing image cleaning instructions.

**Comment by sammcj** [comment]
Thanks, I can confirm the new release fixed the issue:

```
pip install -U data-formulator

data_formulator -p 5009
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator/agents/agent_utils.py:16: SyntaxWarning: invalid escape sequence '\W'
  var_name = re.sub('\W|^(?=\d)','_', var_str)
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator/agents/agent_code_explanation.py:77: SyntaxWarning: invalid escape sequence '\h'
  user_query = f"[CONTEXT]\n\n{data_summary}\n\n[CODE]\n\here is the transformation code: {code}\n\n[EXPLANATION]\n"
/Users/samm/.venv/lib/python3.12/site-packages/data_formulator
 * Serving Flask app 'data_formulator.app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5009
 * Running on http://192.168.0.75:5009
```

And it opened without issue.
